export type { ChannelName, DeepPartial, GhostoConfig } from './config'
export { defaultConfig } from './config'
export { Mascot, MascotBubbleFollower } from './mascot'
export { MascotCanvas } from './mascot-canvas'
export { useMascotChannels } from './use-mascot-channels'
export { useMascotPose } from './use-mascot-pose'
